### ISSUE TITLE
Change Birthday Format to: DD/MM/YYYY (Signup citizen, Personal Details, Substitute Decision Maker Screens)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#103]

**Comment by isabeen** [comment]
@danialshakeel 
birthday format issue in Personal Details Screen: Shows the format mm/dd/yyyy and after some time shows the right format i.e. dd/mm/yyyy

![vv](https://user-images.githubusercontent.com/53593496/68113838-76dbf200-ff16-11e9-84aa-5c83eb3c8fb1.jpg)

**Comment by qamar-sofit** [comment]
@isabeen solved
