### ISSUE TITLE
Personal Details Screen: 1st digit of phone number not showing

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#104]

**Comment by isabeen** [comment]
@danialshakeel phone number omitting 1st digit in personal details screen.

No text in the editable field.

**Comment by isabeen** [comment]
@danialshakeel phone number omitting 1st digit in personal details screen.

**Comment by qamar-sofit** [comment]
@isabeen please upload a screenshot.

**Comment by isabeen** [comment]
@qamar-sofit 

![WhatsApp Image 2019-11-07 at 9 47 05 AM](https://user-images.githubusercontent.com/53593496/68360949-bfc4be00-0143-11ea-8078-a871c3692ce9.jpeg)

**Comment by qamar-sofit** [comment]
solved
