### ISSUE TITLE
Provider Account Creation Screen - View Differences: Check Screenshot 

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#11]
![5- provider account created](https://user-images.githubusercontent.com/53593496/66742243-aa37dd80-ee90-11e9-990f-2a5fbbcdadd0.png)

**Comment by isabeen** [comment]
@HaseemUlHaq the tick icon is now missing.
Title bar is fine.

@qamar-sofit why is the text different here?

**Comment by qamar-sofit** [comment]
The data I created was according to the screens provided initially. They updated the screens later hence the difference. I am looking into it and would update the data accordingly.

**Comment by qamar-sofit** [comment]
UPDATE: This text is not sent from the backend. Only the text of ACD screens is sent from the backend.

**Comment by HaseemUlHaq** [comment]
@maryam-awan need this tick image

**Comment by isabeen** [comment]
@HaseemUlHaq why is the text different?
