### ISSUE TITLE
Process for correct witnessing: Email not generating the selected bullet points

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#139]

**Comment by isabeen** [comment]
@danialshakeel @qammarkhurshid please find a way around

**Comment by danialshakeel** [comment]
<img width="369" alt="Screenshot 2019-11-19 at 2 49 14 PM" src="https://user-images.githubusercontent.com/40662656/69136303-6dd54e00-0adc-11ea-8bea-179fb0c5e952.png">
<img width="964" alt="Screenshot 2019-11-19 at 2 50 10 PM" src="https://user-images.githubusercontent.com/40662656/69136306-6e6de@isabeen 80-0adc-11ea-953f-8642205fec14.png">
<img width="962" alt="Screenshot 2019-11-19 at 2 51 17 PM" src="https://user-images.githubusercontent.com/40662656/69136307-6e6de480-0adc-11ea-8514-904a72163b36.png">

@qammarkhurshid @isabeen

**Comment by isabeen** [comment]
@qammarkhurshid I'm also not getting any bullet points in the email.

**Comment by isabeen** [comment]
If user unchecks a bullet, it is still added in the email. @qammarkhurshid
