### ISSUE TITLE
2a: Minor text changes (see details)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#163]
Look at the highlighted parts and make the following changes.

- Add a full stop after 'form'
- Replace 'another' with 'any'
- Makerss: Change it to 'Makers.'

![b94026cc-f2f9-4928-8b78-f666a427375d](https://user-images.githubusercontent.com/53593496/69117959-664d7f00-0ab3-11ea-8a88-416408ff9707.jpg)

**Comment by qammarkhurshid** [comment]
Following is handled from the FRONT END (the last check)
- Replace 'another' with 'any'
- Makerss: Change it to 'Makers.'
