### ISSUE TITLE
2a Screen: adjust space and full stop (see screenshot)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#164]
See the highlighted areas and make the following changes:

- Add full stop after '(decisions).'
- Remove full stop before '-Appoint'
- Remove space before If

![9440d70f-640e-46c2-95d4-64433aead526](https://user-images.githubusercontent.com/53593496/69118779-6ac76700-0ab6-11ea-9f1c-c45c74dd9746.jpg)

**Comment by qammarkhurshid** [comment]
Resolved.
