### ISSUE TITLE
2b- Condition for Appointment -> Some Text Missing

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#17]
![Screenshot (336)](https://user-images.githubusercontent.com/53593496/66749561-96e23d80-eea3-11e9-806f-8568af651de1.png)

**Comment by qamar-sofit** [comment]
@HaseemUlHaq  this text has been sent in 'question' tag of the related json object.

**Comment by isabeen** [comment]
@maryam-awan please verify this so I can close this

**Comment by isabeen** [comment]
@qamar-sofit I am unable to find any ? tag related to this.

**Comment by isabeen** [comment]
@HaseemUlHaq you didn't show this text?

**Comment by HaseemUlHaq** [comment]
Normal font was supposed to be in "description", Questions are only entertained in few screens where specifically mentioned.
I fixed it for this screen, will provide the build at day end.
