### ISSUE TITLE
Remove Extra spaces from the following screens. (see highlighted areas)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#170]
`1`
![18463a8c-23ef-442b-9036-f0588361eb31](https://user-images.githubusercontent.com/53593496/69124198-124b9600-0ac5-11ea-902b-a951d6032d2d.jpg)
`2`
![76d817b7-528f-4849-bc0c-0a9ec2f0efa4](https://user-images.githubusercontent.com/53593496/69124396-96058280-0ac5-11ea-8645-d260a50e6ea7.jpg)
`3`

**Comment by qammarkhurshid** [comment]
Resolved.
