### ISSUE TITLE
3: (B, D and F Screens) Add colon at the end of text like added in other screens (text along the ?) 

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#175]
For example, see the design below:

![image (30)](https://user-images.githubusercontent.com/53593496/69133385-a0c91300-0ad7-11ea-9687-6b8d9d9f2f33.png)

**Comment by danialshakeel** [comment]
@isabeen from backEnd

**Comment by qammarkhurshid** [comment]
Colon added to the text of D & F. B does not have one.

**Comment by isabeen** [comment]
@qammarkhurshid add it to B as well for consistency. 
There is inconsistency in the design provided. Add it in-front of the round bracket
