### ISSUE TITLE
Provider -> Individual Citizen Screen: Scroll issue. Screen omitting.

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#179]
![c8ed4500-8a74-43f6-b923-e9d229f64ee7](https://user-images.githubusercontent.com/53593496/69137542-c9a0d680-0ade-11ea-9a44-ce5c80930b02.jpg)

**Comment by danialshakeel** [comment]
screen is not scrollable ??

**Comment by isabeen** [comment]
@danialshakeel it is scrolling but from bottom it is omitting. Please check

**Comment by danialshakeel** [comment]
a short screen record ?? no issue on my device

**Comment by isabeen** [comment]
@danialshakeel I've teams you.
