### ISSUE TITLE
Provider -> Individual User Screen: The checkbox tick is not appearing for users with complete ACDs

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#180]
![c8ed4500-8a74-43f6-b923-e9d229f64ee7](https://user-images.githubusercontent.com/53593496/69137784-3e741080-0adf-11ea-951f-ec6580529881.jpg)

**Comment by danialshakeel** [comment]
@isabeen I  was looking into it, but i am not receiving the complete check from backend, do ask @qammarkhurshid if he know something.

**Comment by danialshakeel** [comment]
we hava to checks for complete in useracd.

**Comment by isabeen** [comment]
The users with ACD pdfs present must show ticks

**Comment by isabeen** [comment]
@danialshakeel you've added ticks on the provider home screen instead of the screen which I attached above.

This is totally wrong because a whole user has many other elements, not just and ACD.

![WhatsApp Image 2019-11-19 at 4 28 43 PM](https://user-images.githubusercontent.com/53593496/69143056-f4dcf300-0ae9-11ea-926c-5b1bdfc9beac.jpeg)

**Comment by isabeen** [comment]
@danialshakeel it's even checking the boxes for users with no ACDs.
 Example for the user **'C dan'**
