### ISSUE TITLE
Bold the words in the following screens. (screenshot attached)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#191]
![nnn](https://user-images.githubusercontent.com/53593496/69719999-7f999f80-1133-11ea-8a65-7f9bad75dab0.jpg)

![cats](https://user-images.githubusercontent.com/53593496/69787000-5f261f80-11dd-11ea-8878-43d339df38f8.jpg)

![jjjj](https://user-images.githubusercontent.com/53593496/69935394-90ad2c80-14f6-11ea-9424-eb52594e4090.jpg)

**Comment by danialshakeel** [comment]
all of the text is dynamic from backend, it cannot be stylised in between a paragraph, we can come up to a solution later if it is necessary.

**Comment by isabeen** [comment]
@maryam-awan Please update about this.
