### ISSUE TITLE
Remove the following textual issues. (screenshots attached)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#192]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/53593496/69720266-0a7a9a00-1134-11ea-8557-ff749bd15d0b.png)
![nn](https://user-images.githubusercontent.com/53593496/69720267-0a7a9a00-1134-11ea-90ef-4470921a1d66.jpg)

**Comment by isabeen** [comment]
@danialshakeel please check if the second picture has to do something with front end

**Comment by qammarkhurshid** [comment]
Tabs added. 
- 'Text missing' : Already present in JSON, rest would be handled by front end.

**Comment by isabeen** [comment]
@qammarkhurshid you also handled the extra space in picture no. 1?
