### ISSUE TITLE
PDF Header: Date of Birth Not Showing, Address issues, and Second Given name field should blank

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#194]
![WhatsApp Image 2019-11-27 at 4 53 33 PM](https://user-images.githubusercontent.com/53593496/69721596-013efc80-1137-11ea-8354-5cf524730345.jpeg)

![cats](https://user-images.githubusercontent.com/53593496/69778170-2e39f080-11c5-11ea-8266-1025b25858fb.jpg)

**Comment by qammarkhurshid** [comment]
Resolved.

**Comment by isabeen** [comment]
If address is long, it goes out of the line.
My proposed solution is that we can decrease the font size a bit. We can make the font size and style similar to the default PDF text.

@qammarkhurshid @maryam-awan 
![b0ceffbb-5801-4c4b-a694-82413b4253b2](https://user-images.githubusercontent.com/53593496/70029471-0386d800-15c9-11ea-9395-6d060fb6b79f.jpg)

**Comment by qammarkhurshid** [comment]
Decreased Font Size
