### ISSUE TITLE
Any Screen in 7 step/Anticipatory Prescribing -> Logbook: The back arrow in logbook takes to home screen instead of the previous screen.

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#195]
In ACD, the back arrow takes the user to the previous screen which is perfectly fine, however in 7 step/Anticipatory Prescribing sections, when user clicks logbook from any of the screens and clicks back arrow from there, it takes the user to home screen, instead of the screen from where the log book icon was clicked.

**Comment by danialshakeel** [comment]
done ,, will be live in next publish
