### ISSUE TITLE
Add new/see existing 7 step pathway screen changes. (see screenshot)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#203]
![cats](https://user-images.githubusercontent.com/53593496/69794943-065e8300-11ed-11ea-917d-9e844aa603a0.jpg)

**Comment by isabeen** [comment]
@danialshakeel what about title?
Please confirm if title in design is wrong @maryam-awan

**Comment by danialshakeel** [comment]
In y opinion the title should be 7 Step Pathway, as we are coming from start and making decision wether to view an old one or create new
