### ISSUE TITLE
Resources Upload: Added 15 pictures and clicked forward arrow. The screen keeps on loading but nothing happens.

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#211]
![WhatsApp Image 2019-11-29 at 11 36 44 AM](https://user-images.githubusercontent.com/53593496/69849096-9f4cd700-129d-11ea-9a90-279187456d7f.jpeg)

**Comment by isabeen** [comment]
@danialshakeel still checked, nothing happened. (checked for around 15 minutes)

**Comment by danialshakeel** [comment]
@isabeen danii.shakeel@gmail.com pass 123456 , this account contains pdf with 15 images, i have verified it on my side,, please check again by clearing the cache
