### ISSUE TITLE
Back Button not working on some screens. (see screenshots)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#22]
**WEB**
![1](https://user-images.githubusercontent.com/53593496/66804967-41f30580-ef3d-11e9-9d8c-810296840b60.jpg)

**WEB**
![2](https://user-images.githubusercontent.com/53593496/66804972-45868c80-ef3d-11e9-8878-523730459b23.jpg)

**IOS**
![Back arrow not working](https://user-images.githubusercontent.com/53593496/66898241-40474180-f012-11e9-9ca9-07c09de35029.jpeg)

**Comment by danialshakeel** [comment]
These both are main screens for provider and for citizen,, the back button is to be removed from them,, right ?

**Comment by isabeen** [comment]
As the arrow was in the design, it would be removed once confirmed by the client. @maryam-awan
