### ISSUE TITLE
Following 4 screens are missing in the flow. (Substitute decision makers onward)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#223]
![bbbb](https://user-images.githubusercontent.com/53593496/70622192-34a47f80-1c3d-11ea-98e8-bcf9eb21006f.PNG)

**Comment by danialshakeel** [comment]
Fixed

**Comment by isabeen** [comment]
@danialshakeel move it to the ready for testing column, when available for testing.
