### ISSUE TITLE
3- G: Refusal of Health Care: curly brackets used in text. (see screenshot)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#23]
![nnnn](https://user-images.githubusercontent.com/53593496/66806002-d6f6fe00-ef3f-11e9-8e14-3b3cd37ed697.JPG)

**Comment by HaseemUlHaq** [comment]
@qamar-sofit

**Comment by qamar-sofit** [comment]
This issue has been fixed.
