### ISSUE TITLE
Witness Hint Screen: Some text Missing. Please adjust spacing and alignment according to provided XD.

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#230]
![cats](https://user-images.githubusercontent.com/53593496/70626519-70901280-1c46-11ea-9e12-d324ce6b7d46.jpg)

**Comment by qammarkhurshid** [comment]
JSON file has the text. Text is long so there might be a problem at the front-end. Dani bhai will tell you more about it.

**Comment by danialshakeel** [comment]
missing data added, line breaks are from back-end

**Comment by isabeen** [comment]
@qammarkhurshid  can you you adjust spacing?

**Comment by qammarkhurshid** [comment]
@isabeen Upload the current look so I can adjust the spaces accordingly.

**Comment by isabeen** [comment]
@qammarkhurshid 
Few spaces required in the upper half. Please check.

![jjj-vert](https://user-images.githubusercontent.com/53593496/70987539-ecc0a500-20e1-11ea-9f52-80e77e9c9a64.jpg)

**Comment by qammarkhurshid** [comment]
Fixed!
