### ISSUE TITLE
Final Review Screen: Change the text ACD to ACS.

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#236]
![mmmm](https://user-images.githubusercontent.com/53593496/70685783-379a8100-1ccc-11ea-9af6-957ca8ad9dff.jpg)

**Comment by qammarkhurshid** [comment]
In JSON file and data base it's ACD in case of Southern and ACS in case of Northern Territory. So it might be a mix up at the front-end as the screen names are identical with a difference of one word. Northern Territory's App data's screen titles start with 'North'.

**Comment by isabeen** [comment]
@danialshakeel  please have a look at it.
