### ISSUE TITLE
The 'Add one more page' initially replaces the first image, instead of adding a new one.

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#237]
![WhatsApp Image 2019-12-12 at 10 59 06 AM](https://user-images.githubusercontent.com/53593496/70692278-cdd6a300-1cdc-11ea-9376-23f75ee071de.jpeg)

**Comment by danialshakeel** [comment]
The title and images attached are different.

**Comment by isabeen** [comment]
@danialshakeel check now.
