### ISSUE TITLE
Southern Territory: Change the text Advanced Care Statement to 'Advanced Care Directive' in the following screens

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#239]
![WhatsApp Image 2019-12-12 at 11 24 20 AM](https://user-images.githubusercontent.com/53593496/70687813-06bd4a80-1cd2-11ea-861c-1ff29c2934df.jpeg)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/53593496/70691910-0f1a8300-1cdc-11ea-8c5f-3c9b5d850376.png)

**Comment by qammarkhurshid** [comment]
In JSON file and data base it's ACD in case of Southern and ACS in case of Northern Territory. So it might be a mix up at the front-end as the screen names are identical with a difference of one word. Northern Territory's App data's screen titles start with 'North'.

**Comment by qammarkhurshid** [comment]
![image](https://user-images.githubusercontent.com/52961483/70691710-8dc2f080-1cdb-11ea-8f3f-877cd452c498.png)

**Comment by qammarkhurshid** [comment]
![image](https://user-images.githubusercontent.com/52961483/70691813-cd89d800-1cdb-11ea-8a1d-00f157b336a7.png)

**Comment by isabeen** [comment]
@danialshakeel please have a look at it.
