### ISSUE TITLE
5- Interpreter Statement: The'?' button is inactive for interpreter statement

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#24]
![nnnnnnn](https://user-images.githubusercontent.com/53593496/66806834-f1ca7200-ef41-11e9-8ac1-5355cc481d2a.jpg)

**Comment by isabeen** [comment]
**This screen is missing.** 
![image (38)](https://user-images.githubusercontent.com/53593496/66910292-b6a26e80-f027-11e9-8d74-c164629a9e17.png)

**Comment by isabeen** [comment]
@danialshakeel one of the ? for interpreter screen has been added.
The other ? screen for then ? on next screen is still missing:

We can discuss this flow with later today @maryam-awan @danialshakeel 

![bbbb](https://user-images.githubusercontent.com/53593496/67179497-e8cd1b00-f3ef-11e9-845f-afa6022496dc.png)

**Comment by danialshakeel** [comment]
@isabeen no further flow provided in XD.

**Comment by isabeen** [comment]
@danialshakeel this screen which I attached isn't available to you?

**Comment by isabeen** [comment]
@HaseemUlHaq  will finalize this task after discussion
