### ISSUE TITLE
6-> The Advanced Care Directive Information Statement: Wrong Title and text used on this screen, Arrow sign on button is also opposite(check screenshot)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#26]
![Screenshot (343)](https://user-images.githubusercontent.com/53593496/66809295-8040f280-ef46-11e9-96b0-14514258ba4b.png)

ARROW SIGN IS OPPOSITE:

![Screenshot (344)](https://user-images.githubusercontent.com/53593496/66809693-4e7c5b80-ef47-11e9-86b6-52e6597a0c47.png)

**Comment by danialshakeel** [comment]
@isabeen All of the texts are coming from back-end.

**Comment by isabeen** [comment]
@qamar-sofit please make sure the text sent is according to the XD.

**Comment by qamar-sofit** [comment]
@isabeen Fixed!
