### ISSUE TITLE
6-> Full List of Witness Categories: Wrong title, wrong text, downloads the wrong file (check screenshot)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#27]
6-> Full List of Witness Categories: Wrong title, wrong text, downloads the wrong file (check screenshot)

![Screenshot (347)](https://user-images.githubusercontent.com/53593496/66811369-643f5000-ef4a-11e9-9ae5-282571ac668e.png)

**Comment by isabeen** [comment]
@HaseemUlHaq I think even the arrow should be backwards.

**Comment by danialshakeel** [comment]
> @HaseemUlHaq I think when the next arrow is clicked, the following screen would come, as it was missing:
> 
> **Process for correct witnessing**
> 
> ![image (52)](https://user-images.githubusercontent.com/53593496/66822286-61018f80-ef5d-11e9-95f4-f8f21337d6db.png)

i believe this screen comes up when you click ? on the witness screen.

**Comment by isabeen** [comment]
@danialshakeel let's decide this during discussion session

**Comment by isabeen** [comment]
@HaseemUlHaq There are missing screens.
We need to discuss this part. Closing this issue to avoid confusion.
Will create a new issue.
