### ISSUE TITLE
Citizen/patient Details Screen: Birthday, GP, Mobile fields are wrong.

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#290]
Birthday field says ‘Invalid date’ and Mobile, GP are the name of citizen which is wrong.

![cats](https://user-images.githubusercontent.com/53593496/72521238-e1959c00-387c-11ea-90e9-f0940e035bba.jpg)

**Comment by malikfarhan183** [comment]
I am Preventing the Admin to Change the Email in Citizen/Patient Details.
