### ISSUE TITLE
Provider Signup Use case (Issue)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#292]
**What is happening**: The provider signs up but does not enter verification code yet.
It starts to appear in the admin panel and the admin approves the provider who has not verified his/her email yet.
Now, when the provider enters verification code and continues, nothing happens. (Stuck)

**What is expected:** The provider account should not be visible in the admin panel before the verification of email id.

**Comment by qammarkhurshid** [comment]
Fixed!
