### ISSUE TITLE
ACD count not increasing for adding ACDs from the same account.

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#296]

**Comment by qammarkhurshid** [comment]
Try with an account whose ACD has not been created. 
 > Create a new ACD and check the count. (count should increase by one)
> Then Change the Territory and again check the count. (count should increase by one)
> Update the ACD of any territory and then check the count (count should remain same)

Technically, when a  patient UPDATES an ACD and generates a new PDF, he does not create a new ACD, rather he just updates his answers and other info. So it's the same ACD and does not count as new and hence the count remains same. Confirm this use case with Maryam too.
