### ISSUE TITLE
Error creating citizen from admin panel. (Birthday and Pending Status)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#307]
**The status should be 'Approved'** as the user does not have to enter the code for verification.
The user is getting email and is able to login.

Birthday value is shown by default which is wrong.

![hmgjhg](https://user-images.githubusercontent.com/53593496/72959731-2ebdc480-3dcd-11ea-9245-9b4af57202c3.PNG)

**Comment by qammarkhurshid** [comment]
Fixed the Approval Status.
Birthday will be fixed by Farhan
