### ISSUE TITLE
Groups: Edit and add a provider->click 'Done' : Blank screen appears

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#308]
![aaaa](https://user-images.githubusercontent.com/53593496/72960700-8873be00-3dd0-11ea-8816-ea256ce98440.PNG)

**Comment by malikfarhan183** [comment]
Working Fine For Me. Can You Gave Proper Scenrio So That I Can Resolve.

**Comment by isabeen** [comment]
Its only occurring in my laptop. When I press 'End' key to find and click the 'Done' button, it keeps me at the bottom of screen which is blank. I have to scroll to top manually to see the screen content/
