### ISSUE TITLE
Southern ACD: PDFs missing in the following 4 screens (Section 6)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#314]
![WhatsApp Image 2020-02-10 at 10 26 16 AM (3)](https://user-images.githubusercontent.com/53593496/74123334-45975000-4bf0-11ea-85bf-57e794ebcdd3.jpeg)
![WhatsApp Image 2020-02-10 at 10 26 16 AM (2)](https://user-images.githubusercontent.com/53593496/74123337-46c87d00-4bf0-11ea-9eaa-be1f96050808.jpeg)
![WhatsApp Image 2020-02-10 at 10 26 16 AM (1)](https://user-images.githubusercontent.com/53593496/74123338-47611380-4bf0-11ea-8572-86e8d6801fe9.jpeg)
![WhatsApp Image 2020-02-10 at 10 26 16 AM](https://user-images.githubusercontent.com/53593496/74123339-47f9aa00-4bf0-11ea-8633-e561405dc87f.jpeg)

**Comment by qammarkhurshid** [comment]
@isabeen User name / email?

**Comment by isabeen** [comment]
@qammarkhurshid  try: sana@mailinator.com
