### ISSUE TITLE
Provider -> Resources: Last Screen: App crashes at the forward button. Replace footer buttons with a single home button for the last screen.

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#315]
![WhatsApp Image 2020-02-10 at 10 40 15 AM](https://user-images.githubusercontent.com/53593496/74123860-f05c3e00-4bf1-11ea-863d-2b0658f27a44.jpeg)

**Comment by danialshakeel** [comment]
changed to home button
