### ISSUE TITLE
4- Binding Refusal of Health Care: Text should be justified. 

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#41]
![bb](https://user-images.githubusercontent.com/53593496/66907952-adaf9e00-f023-11e9-9b78-e9f53d6fb95e.jpg)

**Comment by isabeen** [comment]
Radio button placement has been resolved.
@danialshakeel @qamar-sofit who is responsible for text alignment?

The written text errors are:
- Text is incomplete: section 19 of...... ????
- give space between healthcare (health care)
- spelling error: satate (state)
- spelling error: whan (what)

**Comment by qamar-sofit** [comment]
Fixed the errors, alignment will be fixed by the Frontend.

**Comment by isabeen** [comment]
@HaseemUlHaq @danialshakeel Please do the necessary and let me know when it is ready for testing.

**Comment by isabeen** [comment]
@HaseemUlHaq text is not aligned properly :(

**Comment by isabeen** [comment]
@danialshakeel make this screen's text same as the one that comes after it.
Please let me know if you have any query regarding this.
