### ISSUE TITLE
CITIZEN ACCOUNT: Home Screen: Remove back arrow and Purple Book View.

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#55]
Citizen Account: shakhsdevelopers@gmail.com (123456)

Remove Back Arrow
Replace purple book with ACD and other options screen.

**Comment by danialshakeel** [comment]
The purple book view was removed, the arrow is still there

**Comment by isabeen** [comment]
As the arrow was in the design, it would be removed once confirmed by the client. @maryam-awan
