### ISSUE TITLE
Provider Account: Address shown is wrong. (Top Name Bar and Personal Details Screen)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#58]
![WhatsApp Image 2019-10-17 at 4 20 57 PM](https://user-images.githubusercontent.com/53593496/67004751-6d6f1f00-f0fa-11e9-9994-a7bbbd9ee0d7.jpeg)

**Comment by HaseemUlHaq** [comment]
@isabeen Address is correct, I have check it from response, Can you reverify it again.
