### ISSUE TITLE
iOS (Citizen Account): App crashing after three to four clicks

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#59]
ACD -> Personal Details -> Next arrow: App crashes

![WhatsApp Image 2019-10-17 at 4 26 17 PM](https://user-images.githubusercontent.com/53593496/67004992-f8501980-f0fa-11e9-822b-520fa941e214.jpeg)

**Comment by danialshakeel** [comment]
@isabeen is it still occuring ?
