### ISSUE TITLE
Screen Flow Error: The Tick Screen Should appear after clicking 'Upload to My Health Record' button, not before it. 

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#67]
![WhatsApp Image 2019-10-22 at 3 46-horz](https://user-images.githubusercontent.com/53593496/67279023-a7b63300-f4e3-11e9-9280-46ef672d5c01.jpg)

**Comment by HaseemUlHaq** [comment]
@maryam-awan ?

**Comment by isabeen** [comment]
@maryam-awan  @HaseemUlHaq 
as per the discussion, the tick screen would be used later on.
