### ISSUE TITLE
Login Screen View Differences: Check Screenshot

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#7]
**Note:** I am just comparing to the images on Asana boards, I am not aware of changes in requirements (if any). 
 

![1- login](https://user-images.githubusercontent.com/53593496/66741436-fa15a500-ee8e-11e9-8e27-cf38ba91b487.png)

**Comment by HaseemUlHaq** [comment]
@isabeen Username was replaced with email.

**Comment by isabeen** [comment]
@HaseemUlHaq Okay as discussed font colors would be dealt with later.
