### ISSUE TITLE
3 ->G: Refusal of Health care (hint text issues)

### ISSUE THREAD

**Issue by isabeen** [sofittech/palcare-project#84]
![cats](https://user-images.githubusercontent.com/53593496/67380727-34282a80-f5a4-11e9-99f3-b6f62f513fa0.jpg)

**Comment by qamar-sofit** [comment]
No issue from backend.

**Comment by isabeen** [comment]
@qamar-sofit Remove all \n from "instructions": ["Some suggested statements.\n\n"],

**Comment by qamar-sofit** [comment]
Fixed!
