### ISSUE TITLE
Verification Code Screen: Bottom part of screen is blank for bigger screen size

### ISSUE THREAD

**Issue by aqibbangash** [sofittech/palcare-project#90]
Should not be scrollable.

https://share.icloud.com/photos/0y4FkFmKRwg5GhJNL0aTz0AxA

**Comment by aqibbangash** [comment]
@isabeen Please invalidate the issue if already mentioned.

**Comment by isabeen** [comment]
@danialshakeel  have a look.
Profile avarat icon is also overlapping margins a bit.

![Uploading MicrosoftTeams-image.png…]()

**Comment by isabeen** [comment]
@danialshakeel 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/53593496/68577017-0cd0c900-0491-11ea-8516-ae77a0e1b2f6.png)

**Comment by isabeen** [comment]
@danialshakeel please increase the size of purple background as well.
